### ISSUE TITLE
Publication addition request

### ISSUE THREAD

**Issue by MherMatevosyan** [GuoJeff/generative-drug-design-with-experimental-validation#1]
Hi,

We have published an RL-based approach with in vitro and in vivo results which is not present in your list: [link](https://doi.org/10.1016/j.antiviral.2024.105818)

Happy to make changes and provide more information if needed.

**Comment by GuoJeff** [comment]
Hi @MherMatevosyan,

Thank you for sharing your work! I will add it ASAP

**Comment by GuoJeff** [comment]
I have added the paper now! Thank you for sharing your work!
